"""empty message

Revision ID: 469e5f3e2fc9
Revises: 1f0c7bbe8aaf
Create Date: 2026-04-04 21:21:30.800833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '469e5f3e2fc9'
down_revision = '1f0c7bbe8aaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=False))
        batch_op.drop_column('property_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('type')

    # ### end Alembic commands ###
